### ISSUE TITLE
Permission to contribute spack logo to devicons/nerd-fonts

### ISSUE THREAD

**Issue by dennisklein** [spack/spack.io#55]
Hi,

I found
* https://github.com/spack/spack.io/blob/main/assets/images/spack-logo.svg
* https://github.com/spack/spack.io/blob/main/assets/images/spack-logo-white.svg

in this repo. Are those the official logo sources?

Secondly, may I use those to attempt contributing a spack logo glyph to https://github.com/devicons/devicon?

The motivation is this:
* Devicons get included into https://github.com/ryanoasis/nerd-fonts
* which would enable all kinds of nice things (e.g. I would like to write a spack environment segment for my https://github.com/romkatv/powerlevel10k shell prompt)

What do you think?

**Comment by tgamblin** [comment]
Yep those are the sources we used to generate the logos we use in presentations.  You can use definitely them for a font like this -- I think it would be great to get the spack symbol more widely included in stuff like nerd-fonts!  Go for it.
